AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - config.ru
    - Rakefile
    - bin/**/*
    - config/**/*
    - db/**/*
    - doc/**/*
    - node_modules/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - tmp/**/*
    - vendor/**/*

Metrics/AbcSize:
  Max: 75

Metrics/BlockLength:
  Max: 250

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 75

Metrics/ModuleLength:
  Max: 400

Metrics/PerceivedComplexity:
  Max: 20

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: no_space

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent
