source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '6.0.3.4'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'jbuilder'
gem 'rails-i18n'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'webpacker'

# ActiveJob Backend
gem 'daemons'
gem 'delayed_job_active_record'

# Authorization
gem 'devise'

# AWS SDK
gem 'aws-sdk'
gem 'aws-sdk-rails'

# Frontend
gem 'bootstrap', '~> 4.5.3'
gem 'sass-rails', '~> 6.0'
gem 'slim-rails'

## PDF
gem 'prawn'
gem 'prawn-table'

## Others
gem 'chartkick'
gem 'figaro'
gem 'gon'

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.4'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'chromedriver-helper'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'selenium-webdriver'
  gem 'simplecov'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
