source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'
gem 'rails', '~> 5.2.3'


# Default Gems
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.12'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

# User added
gem 'chartkick'
gem 'figaro'
gem 'gon'
gem 'mini_racer', platforms: :ruby
gem 'rails-i18n'

## ActiveJob Backend
gem 'daemons'
gem 'delayed_job_active_record'

## AWS SDK
gem 'aws-sdk'
gem 'aws-sdk-rails'

## Frontend
gem 'bootstrap', '~> 4.1.1'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'sass-rails', '~> 5.0'
gem 'slim-rails'

## PDF
gem 'prawn'
gem 'prawn-table'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'chromedriver-helper'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'selenium-webdriver'
  gem 'simplecov'
end
