source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'active_model_serializers'
gem 'bcrypt', '~> 3.1.16'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'daemons'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'devise'
gem 'enum_help'
gem 'pg', '>= 0.18', '< 2.0'
gem 'prawn'
gem 'prawn-table'
gem 'puma', '~> 5.2'
gem 'rails', '6.1.3.1'
gem 'rails-i18n'
gem 'slim-rails'
gem 'turbolinks', '~> 5'
gem 'webpacker'

## should import by npm
gem 'chartkick'
gem 'figaro'
gem 'gon'

group :development do
  gem 'byebug'
  gem 'html2slim'
  gem 'listen', '>= 3.0.5', '< 3.6'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'selenium-webdriver'
  gem 'simplecov'
end

group :production do
  gem 'aws-sdk-s3'
end 
