version: '2'
services:
  db:
    image: postgres:10.6
    ports:
      - "5432:5432"
    volumes:
      - ./application/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rakuraku_komagumi
      - POSTGRES_PASSWORD=password
  application:
    build:
      context: ./application
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    working_dir: /root/rakuraku_komagumi
    command: /bin/bash --login -c "./startup.sh"
    volumes:
      - ./application:/root/rakuraku_komagumi
      - ./application/vendor/bundle:/root/rakuraku_komagumi/vendor/bundle:delegated
    environment:
      - RAILS_ENV=development
      - BUNDLE_APP_CONFIG=/root/rakuraku_komagumi/.bundle
      - DATABASE_HOST=db
      - DATABASE_USERNAME=rakuraku_komagumi
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=development
    depends_on:
      - db
  webpack-dev-server:
    build:
      context: ./application
      dockerfile: ./Dockerfile
    ports:
      - "3035:3035"
    working_dir: /root/rakuraku_komagumi
    command: /bin/bash --login -c "bin/yarn && bin/webpack-dev-server --hot --inline"
    volumes:
      - ./application:/root/rakuraku_komagumi
      - ./application/vendor/bundle:/root/rakuraku_komagumi/vendor/bundle:delegated
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    depends_on:
      - application
