version: 2.1
jobs:
  test-application:
    docker:
      - image: circleci/ruby:3.0.0-node
        name: application
      - image: postgres:10.6
        name: db
        environment:
          POSTGRES_USER: rakuraku_komagumi
          POSTGRES_PASSWORD: password
      - image: selenium/standalone-chrome:latest
        name: chrome
    steps:
      - checkout
      - run:
          name: install library
          command: bundle && yarn
          working_directory: ~/project/application
      - run:
          name: create database
          command: bundle exec rails db:reset
          working_directory: ~/project/application
      - run:
          name: rubocop
          command: bundle exec rubocop
          working_directory: ~/project/application
      - run:
          name: rspec
          command: bundle exec rspec
          working_directory: ~/project/application
  test-optimization:
    docker:
      - image: circleci/python:3.7.8
        name: optimization
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: pip install --upgrade pip
          working_directory: ~/project/optimization
      - run:
          name: install pip
          command: pip install numpy psycopg2 awscli pycodestyle autopep8 line_profiler
          working_directory: ~/project/optimization
      - run:
          name: pycodestyle
          command: pycodestyle . --ignore="E501,W503,W504"
          working_directory: ~/project/optimization
      - run:
          name: unittest
          command: python -m unittest discover 
          working_directory: ~/project/optimization

workflows:
  version: 2
  test-workflow:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - test-application:
          requires:
            - hold
      - test-optimization:
          requires:
            - hold
