room = Room.create(name: '教室名')
Teacher.create(room: room, name: '講師０１', email: 'teacher1@example.com')
Student.create(room: room, name: '生徒０１', email: 'student1@example.com', school_grade: 21)
Tutorial.create(room: room.id, name: '国語', short_name: '国', order: 1)
Tutorial.create(room: room.id, name: '数学', short_name: '数', order: 2)
Tutorial.create(room: room.id, name: '英語', short_name: '英', order: 3)
Tutorial.create(room: room.id, name: '理科', short_name: '理', order: 4)
Tutorial.create(room: room.id, name: '社会', short_name: '社', order: 5)
Group.create(room: room.id, name: '理科', short_name: '理', order: 1)
Group.create(room: room.id, name: '社会', short_name: '社', order: 2)
