openapi: 3.0.3
info:
  title: rakuraku_komagumi
  description: '最適化モジュール向けAPI'
  version: 1.0.0
servers:
- url: http://localhost:3000/optimization
- url: https://dev.rakuraku-komagumi.com/optimization
- url: https://stg.rakuraku-komagumi.com/optimization
- url: https://rakuraku-komagumi.com/optimization
tags:
- name: term
  description: 期間API
paths:
  /terms/{termId}:
    $ref: ./paths/terms-by-id.yml
  /terms/{termId}/log:
    $ref: ./paths/terms-by-id-log.yml
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
