@startuml term_schedule_data_model

package "期間の予定データモデル" {
  entity "rooms" #F0F0F0 {
    + id : 教室ID [PK]
    --
  }

  entity "terms" {
    + id : 期間ID [PK]
    --
    # room_id : 教室ID [FK]
    name : 名前
    year : 年度
    term_type : 期間種別
    begin_at : 開始日
    end_at : 終了日
    period_count : 時限数
    seat_count : 座席数
    position_count : 座席あたりの生徒数
  }

  entity "student_optimization_rules" {
    + id : 生徒の予定最適化ルール
    --
    # term_id : 期間ID [FK]
    school_grade : 対象期間における学年
    occupation_limit : １日の最大コマ数
    occupation_costs : １日のコマ数に対するコスト値
    blank_limit : １日の最大空きコマ数
    blank_costs : １日の空きコマ数に対するコスト値
    interval_cutoff : 科目の受講日数間隔のカットオフ値
    interval_costs : 科目の受講日数間隔に対するコスト値
  }

  entity "teacher_optimization_rules" {
    + id : 講師の予定最適化ルール
    --
    # term_id : 期間ID [FK]
    single_cost : １対１授業のコスト値
    different_pair_cost : 違う科目を同時に教える時のコスト値
    occupation_limit : １日の最大コマ数
    occupation_costs : １日のコマ数に対するコスト値
    blank_limit : １日の最大空きコマ数
    blank_costs : １日の空きコマ数に対するコスト値
  }

  entity "term_students" #F0F0F0 {
    + id : 期間に紐づいた生徒ID [PK]
    --
  }

  entity "term_teachers" #F0F0F0 {
    + id : 期間に紐づいた講師ID [PK]
    --
  }

  entity "term_groups" #F0F0F0 {
    + id : 期間に紐づいた集団科目ID [PK]
    --
  }

  entity "tutorial_pieces" #F0F0F0 {
    + id : 個別科目のコマID [PK]
    --
  }

  entity "begin_end_times" {
    + id : 開始・終了時刻ID [PK]
    --
    # term_id : 期間ID [FK]
    period_index : 時限インデックス
    begin_at : 開始時刻
    end_at : 終了時刻
  }

  entity "timetables" {
    + id : 時間枠ID [PK]
    --
    # term_id : 期間ID [FK]
    term_group_id : 期間に紐づいた集団科目ID
    date_index : 日付インデックス
    period_index : 時限インデックス
    is_closed : 閉室かどうか
  }

  entity "seats" {
    + id : 座席ID [PK]
    --
    # term_id : 期間ID [FK]
    # timetable_id : 時間枠ID [FK]
    term_teacher_id : 期間に紐づいた講師ID
    seat_index : 座席インデックス
    position_count : 座席あたりの生徒数
  }

  entity "student_vacancies" {
    + id : 生徒の空きID [PK]
    --
    # timetable_id : 時間枠ID [FK]
    # term_student_id : 期間に紐づいた生徒ID [FK]
    is_vacant : 空きかどうか
  }

  entity "teacher_vacancies" {
    + id : 講師の空きID [PK]
    --
    # timetable_id : 時間枠ID [FK]
    # term_teacher_id : 期間に紐づいた講師ID [FK]
    is_vacant : 空きかどうか
  }
}

rooms ||-do-o{ terms
terms ||-up-|{ teacher_optimization_rules
terms ||-up-|{ student_optimization_rules 
terms ||-le-|{ begin_end_times
terms ||-ri-|{ timetables
terms ||-ri-|{ seats
timetables ||-ri-|{ seats
timetables ||-do-|{ student_vacancies
timetables ||-do-|{ teacher_vacancies
term_students ||-up-|{ student_vacancies
term_teachers ||-up-|{ teacher_vacancies
term_groups |o-up-o{ timetables
seats }o-do-o| term_teachers
seats |o-do-o{ tutorial_pieces
@enduml
