development:
  adapter: postgresql
  database: "development"
  username: "rakuraku_komagumi"
  password: "password"
  host: "db"
  pool: 4
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  database: "test"
  username: "rakuraku_komagumi"
  password: "password"
  host: "db"
  pool: 4
  timeout: 5000
  port: 5432

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
